# Generated by Django 4.0.2 on 2022-10-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('silicon', models.CharField(max_length=150)),
                ('nickel', models.PositiveBigIntegerField(null=True)),
                ('copper', models.CharField(max_length=150, null=True)),
                ('metal', models.CharField(max_length=150, null=True)),
                ('queries', models.BooleanField(default=False)),
            ],
        ),
    ]
