# Generated by Django 4.0.2 on 2022-10-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication', '0002_current_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_stock',
            name='nickel',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='current_stock',
            name='queries',
            field=models.BooleanField(max_length=150),
        ),
    ]
