# Generated by Django 4.0.2 on 2022-10-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication', '0003_alter_current_stock_nickel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_stock',
            name='queries',
            field=models.CharField(max_length=150),
        ),
    ]
