# Generated by Django 4.0.2 on 2022-10-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silicon', models.CharField(max_length=150)),
            ],
        ),
    ]
