# Generated by Django 4.0.2 on 2022-10-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molding', '0003_product_send_quantatiy'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='s',
            field=models.BooleanField(default=False),
        ),
    ]
