# Generated by Django 4.0.2 on 2022-10-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molding', '0004_purchase_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_send',
            name='s2',
            field=models.BooleanField(default=False),
        ),
    ]
