# Generated by Django 4.0.2 on 2022-10-12 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fabrication',
            new_name='consumer',
        ),
    ]
