# Generated by Django 4.0.2 on 2022-10-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_company_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('type', models.CharField(max_length=150)),
                ('product', models.CharField(max_length=150, null=True)),
                ('product1', models.CharField(max_length=150, null=True)),
                ('product2', models.CharField(max_length=150, null=True)),
                ('quantatiy', models.CharField(max_length=150, null=True)),
                ('queries', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
