# Generated by Django 4.0.2 on 2022-10-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0004_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='materails',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
