# Generated by Django 4.0.2 on 2022-10-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='send_mold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150)),
                ('range', models.CharField(max_length=150)),
                ('query', models.CharField(max_length=150)),
            ],
        ),
    ]
