# Generated by Django 4.0.2 on 2022-10-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_send_mold_solutionss'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_mold',
            name='silicon_r',
            field=models.BooleanField(default=False),
        ),
    ]
